# spider config toml
# https://github.com/toml-lang/toml

[[spider]]
  name = "kuaidaili"
  url = "https://www.kuaidaili.com/free/inha/1/"
  [spider.rule]
    host = 0
    port = 1
    anonymity = 2
	scheme = 3

[[spider]]
  name = "kuaidaili-2"
  url = "https://www.kuaidaili.com/free/intr/1/"
  [spider.rule]
    host = 0
    port = 1
    anonymity = 2
	scheme = 3

[[spider]]
  name = "ip3366"
  url = "http://www.ip3366.net/"
  [spider.rule]
    host = 0
    port = 1
    anonymity = 2
	scheme = 3

[[spider]]
  name = "freeip"
  url = "https://www.freeip.top/?page=1"
  [spider.rule]
    host = 0
    port = 1
    anonymity = 2
	scheme = 3

[[spider]]
  name = "89ip"
  url = "http://www.89ip.cn/index.html"
  [spider.rule]
    host = 0
    port = 1